export type Platform = "whatsapp" | "line" | "sms" | "test";

export interface InboundMessage {
  platform: Platform;
  channelId: string;
  userId?: string;
  messageId: string;
  timestamp: Date;
  content: {
    type: "text" | "button_reply" | "list_reply" | "image" | "system";
    text?: string;
    buttonId?: string;
    listId?: string;
    rawPayload: unknown;
  };
}

export interface OutboundMessage {
  userId: string;
  platform?: Platform;
  /** Idempotency key generated by the engine so crash-recovery and dispatch can deduplicate sends. */
  idempotencyKey?: string;
  conversationContext: {
    requiresSession: boolean;
    priority: "normal" | "urgent";
  };
  content: {
    type: "text" | "buttons" | "list" | "template";
    text: string;
    buttons?: Array<{ id: string; title: string }>;
    list?: Array<{ id: string; title: string; description?: string }>;
    templateName?: string;
    templateVariables?: Record<string, string>;
  };
}

export interface IMAdapter {
  readonly platform: Platform;
  parseWebhook(payload: unknown): InboundMessage | InboundMessage[];
  buildPayload(message: OutboundMessage): unknown;
  verifySignature?(payload: string | Buffer, signature: string, secret: string): boolean;
  getVerifyChallenge?(query: Record<string, string>): string | null;
}

export interface IMPlatformRegistry {
  getAdapter(platform: Platform): IMAdapter | undefined;
  register(adapter: IMAdapter): void;
}

export class DefaultPlatformRegistry implements IMPlatformRegistry {
  private adapters = new Map<Platform, IMAdapter>();

  register(adapter: IMAdapter): void {
    this.adapters.set(adapter.platform, adapter);
  }

  getAdapter(platform: Platform): IMAdapter | undefined {
    return this.adapters.get(platform);
  }
}
